version: '3'
services:
  nginx:
    image: mskrz/zadanie2:z2_nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - '3050:80'
  api:
    image: mskrz/zadanie2:z2_server
    hostname: server
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: mskrz/zadanie2:z2_client
    hostname: client
    mem_limit: 128m
  worker:
    image: mskrz/zadanie2:z2_worker
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
